### PR TITLE
Updating Trestle master to version 0.2

### PR DESCRIPTION
**Pull request by julianrichen**
Updating Trestle master to version 0.2

### CODE REVIEW

**Comment by FireDart** [comment]
@pedzed If you approve I'll pull.

**Comment by FireDart** [comment]
I'm actually putting this pull on hold, I think I might have solved a major issue.

**Comment by FireDart** [comment]
I think we are go for v0.2. @pedzed If you want to look it over and give me your your opinion please do, your feed back is always welcome.

If you don't have the time let me know and I'll just pull.

**Comment by pedzed** [comment]
> If you don't have the time let me know and I'll just pull.

I'll take a look at it within 3 days.

**Comment by pedzed** [comment]
@FireDart Could you update `.gitignore`? Also, could you take a look at the configs? They're everywhere. Shouldn't they be centralized?

**Comment by FireDart** [comment]
@pedzed Since the log directory in /src/trestle/log is auto generated I'll just ignore the entire directory instead of just the files in it. I also cleaned-up the root .gitignore.

**Comment by FireDart** [comment]
Late addition to 0.2, added disconnect feature and removed some unneeded try/catch blocks in database.php.

**Comment by pedzed** [comment]
@FireDart Could you remove [the codes you commented out](https://github.com/tres-framework/Trestle/blob/0d5280d6e06d21dee089b58e741f9cdc687ed0a4/src/Trestle/Engineer.php#L528-L530)?

**Comment by pedzed** [comment]
@FireDart Any idea what [this DocBlock](https://github.com/tres-framework/Trestle/blob/0d5280d6e06d21dee089b58e741f9cdc687ed0a4/src/Trestle/Engineer.php#L444) was supposed to be?

**Comment by pedzed** [comment]
Shouldn't https://github.com/tres-framework/Trestle/blob/1df5734893e2cfb777b522e43369e6ce334c0142/src/Trestle/Log.php#L185-L187 be removed? It can easily be spoofed.

**Comment by FireDart** [comment]
> @FireDart Could you remove [the codes you commented out](https://github.com/tres-framework/Trestle/blob/0d5280d6e06d21dee089b58e741f9cdc687ed0a4/src/Trestle/Engineer.php#L528-L530)?

I thought I removed that, fixed.

> @FireDart Any idea what this DocBlock was supposed to be?

Fixed.

> Shouldn't [Log.php#L185-L187](https://github.com/tres-framework/Trestle/blob/1df5734893e2cfb777b522e43369e6ce334c0142/src/Trestle/Log.php#L185-L187) be removed? I thought it could be spoofed.

If it can be spoofed then yah, better to remove it. It needs a rework anyway but another time.

**Comment by pedzed** [comment]
What else has to be done? I would like to use this in one of my test projects. It would be nice if this could be merged soon.

**Comment by FireDart** [comment]
I would say done, been playing around with it and it seems to be working for the most part. I'll go ahead and merge it and if any issues arise I'll just patch it with v0.2.1 if need be.

**Pull request merged**
